[package]
name = "spacetraders"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
iced = { version = "0.14.0", features = ["wgpu", "advanced"]}
reqwest = { version = "0.13.2", features = ["json"] }
secrecy = "0.10.3"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
spacetraders_sdk = { path = "api_spec/packages/spacetraders-sdk" }
bytemuck = { version = "1", features = ["derive"] }